server:
  port: 8081
services:
  openai:
    url: https://api.aiproxy.io/v1
    paths:
      completion: "/completions"
      chatCompletion: "/chat/completions"
    headers:
    model:
      "gpt-3.5-turbo"
    key: ""
spring:
  data:
    mongodb:
      uri: ""